spring:
  application:
    name: Brokage Firm

  datasource:
    url: jdbc:h2:mem:brokage
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    path: /
